---
engines:
  brakeman:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  fixme:
    enabled: true
  radon:
    enabled: true
  rubocop:
    enabled: true
    channel: rubocop-0-87
    checks:
      Rubocop/Style/PercentLiteralDelimiters:
        enabled: false # it's outdated vs rubocop
ratings:
  paths:
  - Gemfile.lock
  - "**.erb"
  - "**.haml"
  - "**.rb"
  - "**.rhtml"
  - "**.slim"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
exclude_paths:
- config/
- db/
- test/
