inherit_from:
  - .rubocop_todo.yml

Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.5
  TargetRailsVersion: 5.2
  Exclude:
    - 'extras/**/*'
    - 'locale/**/*'
    - 'node_modules/**/*'

# Just so it looks like core Foreman
Style/HashSyntax:
  EnforcedStyle: no_mixed_keys

Layout/DotPosition:
  EnforcedStyle: 'trailing'

Rails/ActionFilter:
  EnforcedStyle: action

Style/RaiseArgs:
  EnforcedStyle: compact

Style/SymbolArray:
  EnforcedStyle: brackets

Style/FormatStringToken:
  EnforcedStyle: template

Rails/SkipsModelValidations:
  Enabled: false

Metrics:
  Enabled: false

Layout/LineLength:
  Enabled: false

Performance/RegexpMatch:
  Enabled: false
