query($id: String!, $first: Int, $last: Int){
  host(id: $id) {
    id
    allAnsibleRoles(first: $first, last: $last) {
      totalCount
      nodes {
        id
        name
        inherited
        ansibleVariables {
          totalCount
        }
      }
    }
  }
}
