#import "./currentUserAttributes.gql"

query($id: String!, $first: Int, $last: Int) {
  host(id: $id) {
    id
    ownAnsibleRoles(first: $first, last: $last) {
      totalCount
      nodes {
        id
        name
      }
    }
  }
  currentUser {
    ...CurrentUserAttributes
  }
}
