#import "./currentUserAttributes.gql"

query($search: String, $first: Int, $last: Int) {
  jobInvocations(search: $search, first: $first, last: $last) {
    totalCount
    nodes {
      id
      description
      startAt
      statusLabel
      recurringLogic {
        id
        cronLine
      }
      task {
        id
        state
        result
      }
    }
  }
  currentUser {
    ...CurrentUserAttributes
  }
}
