query($id: String!, $hostId: Int!, $match: String) {
  host(id: $id) {
    allAnsibleRoles {
      nodes {
        ansibleVariablesWithOverrides(hostId: $hostId) {
          nodes {
            id
            key
            defaultValue
            parameterType
            ansibleRoleName
            lookupValues(match: $match) {
              nodes {
                id
                match
                value
                omit
              }
            }
            currentValue {
              value
              element
              elementName
            }
          }
        }
      }
    }
  }
}
