query($id: String!, $hostId: Int!) {
  host(id: $id) {
    allAnsibleRoles {
      nodes {
        name
        ansibleVariablesWithOverrides(hostId: $hostId) {
          nodes {
            key
            defaultValue
            parameterType
            currentValue {
              value
              element
              elementName
            }
          }
        }
      }
    }
  }
}

