---
name: Release

on:
  create:
    ref_type: tag

jobs:
  release:
    name: Release gem
    uses: theforeman/actions/.github/workflows/release-gem.yml@v0
    with:
      allowed_owner: theforeman
    secrets:
      api_key: ${{ secrets.RUBYGEM_API_KEY }}
