name: Write cache on merge
  push:
    branches:
    - master
env:
  BUNDLE_WITHOUT: journald:development:console:libvirt
jobs:
  rubocop_cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true
  ruby_cache:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        foreman-core-branch: [develop]
        ruby-version: [2.5, 2.6]
    steps:
      - name: Install build packages
        run: |
          sudo apt-get update
          sudo apt-get install build-essential libcurl4-openssl-dev zlib1g-dev libpq-dev
      - uses: actions/checkout@v2
        with:
          repository: theforeman/foreman
          ref: ${{ matrix.foreman-core-branch }}
      - uses: actions/checkout@v2
        with:
          path: foreman_ansible
      - name: Setup Bundler
        run: |
          echo "gem 'foreman_ansible', path: './foreman_ansible'" > bundler.d/foreman_ansible.local.rb
          echo "gem 'foreman_ansible_core', path: './foreman_ansible'" >> bundler.d/foreman_ansible.local.rb
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
