export const OPEN_YAML_IMPORT_FROM_ROLE = 'OPEN_YAML_IMPORT_FROM_ROLE';
export const OPEN_YAML_IMPORT = 'OPEN_YAML_IMPORT';
export const CLOSE_YAML_IMPORT = 'CLOSE_YAML_IMPORT';

export const DuplicateStatus = {
  NO_DUPLICATE: 0,
  LOCAL_DUPLICATE: 1,
  INSTALLED_DUPLICATE: 2,
};
