export const ANSIBLE_ROLES_REQUEST = 'ANSIBLE_ROLES_REQUEST';
export const ANSIBLE_ROLES_SUCCESS = 'ANSIBLE_ROLES_SUCCESS';
export const ANSIBLE_ROLES_FAILURE = 'ANSIBLE_ROLES_FAILURE';
export const ANSIBLE_ROLES_DUAL_LIST_CHANGE = 'ANSIBLE_ROLES_DUAL_LIST_CHANGE';
