export const ANSIBLE_ROLES_REQUEST = 'ANSIBLE_ROLES_REQUEST';
export const ANSIBLE_ROLES_SUCCESS = 'ANSIBLE_ROLES_SUCCESS';
export const ANSIBLE_ROLES_FAILURE = 'ANSIBLE_ROLES_FAILURE';
export const ANSIBLE_ROLES_ADD = 'ANSIBLE_ROLES_ADD';
export const ANSIBLE_ROLES_REMOVE = 'ANSIBLE_ROLES_REMOVE';
export const ANSIBLE_ROLES_ASSIGNED_PAGE_CHANGE =
  'ANSIBLE_ROLES_ASSIGNED_PAGE_CHANGE';
