export const ANSIBLE_ROLES_REQUEST = 'ANSIBLE_ROLES_REQUEST';
export const ANSIBLE_ROLES_SUCCESS = 'ANSIBLE_ROLES_SUCCESS';
export const ANSIBLE_ROLES_FAILURE = 'ANSIBLE_ROLES_FAILURE';
export const ANSIBLE_ROLES_ADD = 'ANSIBLE_ROLES_ADD';
export const ANSIBLE_ROLES_REMOVE = 'ANSIBLE_ROLES_REMOVE';
export const ANSIBLE_ROLES_ASSIGNED_PAGE_CHANGE =
  'ANSIBLE_ROLES_ASSIGNED_PAGE_CHANGE';
export const ANSIBLE_ROLES_FORM_OBJECT = 'ANSIBLE_ROLES_FORM_OBJECT';
export const ANSIBLE_VARIABLES_REQUEST = 'ANSIBLE_VARIABLES_REQUEST';
export const ANSIBLE_VARIABLES_SUCCESS = 'ANSIBLE_VARIABLES_SUCCESS';
export const ANSIBLE_VARIABLES_FAILURE = 'ANSIBLE_VARIABLES_FAILURE';
export const ANSIBLE_VARIABLES_REMOVE = 'ANSIBLE_VARIABLES_REMOVE';
